POST http://localhost:4004/main/Meals
Content-Type: application/json

{
    "ID": "650cc22b-06f8-4c67-9847-18131f259a77",
    "name": "ThorstensEssen",
    "ingredient": [{"ingredient_ID": "ab5a1fd9-f742-40ec-9582-a0604a7e2740"}]
}

###
POST http://localhost:4004/main/Ingredients
Content-Type: application/json

{
    "meal": [{"meal_ID": "650cc22b-06f8-4c67-9847-18131f259a77"}],
    "name": "Apple",
    "energy": 10,
    "proteins": 5,
    "carbs": 2,
    "fats": 4,
    "fiber": 15
}